In [8]:
import pandas as pd
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
import converter

df = pd.read_csv('../data/car_sales_cleaned1.csv')

df = df.drop_duplicates()  #removing duplicates
df = df.dropna()  # removing rows with missing data
df

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Male,13500,Ford,Expedition,Auto,Black,26000
1,Male,1480000,Dodge,Durango,Auto,Black,19000
2,Male,1035000,Cadillac,Eldorado,Manual,Red,31500
3,Male,13500,Toyota,Celica,Manual,Pale White,14000
4,Male,1465000,Acura,TL,Auto,Red,24500
...,...,...,...,...,...,...,...
23898,Male,530000,Volvo,C70,Manual,Pale White,24000
23900,Female,771000,Ford,Contour,Auto,Red,19000
23902,Female,900000,Chevrolet,Prizm,Auto,Black,16000
23903,Male,705000,BMW,328i,Manual,Red,21000
23905,Male,1225000,Lexus,ES300,Auto,Pale White,27500

In [9]:
model = DecisionTreeClassifier()
y = df[['Model']]
mapper = converter.columns_mapper(['Gender', 'Company', 'Model', 'Transmission', 'Color'], df)
dfConverted = converter.convert_x(df, mapper)
X = dfConverted[['Gender', 'Color']]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)
model.fit(X_train, y_train)
predictions = model.predict(X_test)
score = accuracy_score(y_test, predictions)
score

0.02382121807465619

In [10]:
import joblib

model.fit(X.values, y)
predictions = model.predict([[mapper['Gender']['Female'], mapper['Color']['Pale White']]])
predictions

array(['Jetta'], dtype=object)

In [11]:
joblib.dump(model, '../models/car_gender_model_hw.joblib')

['../models/car_gender_model_hw.joblib']

In [16]:
# show rows for Hyundai Company
dfHyundai = df[df["Company"] == "Hyundai"].reset_index(drop=True)
dfHyundai

,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,Female,535000,Hyundai,Accent,Manual,Black,18000
1,Female,1690000,Hyundai,Sonata,Manual,Black,15000
2,Male,955000,Hyundai,Elantra,Manual,Pale White,26000
3,Male,457000,Hyundai,Sonata,Manual,Pale White,21000
4,Male,13500,Hyundai,Sonata,Manual,Black,20000
...,...,...,...,...,...,...,...
219,Female,1675000,Hyundai,Sonata,Manual,Black,20500
220,Female,13500,Hyundai,Elantra,Manual,Red,22000
221,Female,460000,Hyundai,Sonata,Manual,Black,15000
222,Male,705000,Hyundai,Sonata,Manual,Red,21000
223,Male,681500,Hyundai,Accent,Manual,Black,18500

In [17]:
dfToyotaExp = df.query('Company == "Toyota" and `Price ($)` > 40000').reset_index()
dfToyotaExp

,index,Gender,Annual Income,Company,Model,Transmission,Color,Price ($)
0,239,Male,1350000,Toyota,Tacoma,Auto,Pale White,53000
1,258,Male,1151000,Toyota,Corolla,Auto,Pale White,41100
2,269,Female,825000,Toyota,Tacoma,Manual,Pale White,82000
3,308,Female,13500,Toyota,Corolla,Auto,Pale White,41000
4,358,Male,1326000,Toyota,RAV4,Manual,Black,85600
...,...,...,...,...,...,...,...,...
170,23379,Male,1300000,Toyota,Celica,Auto,Pale White,45001
171,23385,Female,615000,Toyota,Tacoma,Auto,Pale White,53000
172,23443,Male,2400000,Toyota,RAV4,Manual,Black,85000
173,23476,Male,520000,Toyota,Celica,Auto,Pale White,45000
174,23735,Male,1635000,Toyota,Tacoma,Auto,Pale White,53501

In [22]:
most_popular_cars = df[["Company", "Model"]].value_counts().head(3)
most_popular_cars

Company     Model
Chevrolet   Prizm         362
Mitsubishi  Diamante      347
Oldsmobile  Silhouette    337
Name: count, dtype: int64